import axios from 'axios';
import Head from 'next/head'
import List from '../src/list'


export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <header>
          <h1> 제목 </h1>
        </header>
        <List data={data}/>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  let d;
  d = await axios.get('https://port-0-next-mysql-3a9t2ble82e01s.sel3.cloudtype.app/api/'); 
  
  return {
    props:{data:d.data},
  }
}

// getStaticProps, getServerSideProps